####  PBS preamble
#PBS -N FastTree155
#PBS -M marschmi@umich.edu
#PBS -m abe

#PBS -l nodes=1:ppn=5,mem=100gb,walltime=80:00:00
#PBS -V

#PBS -A vdenef_fluxm
#PBS -l qos=flux
#PBS -q fluxm
####  End PBS preamble

#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi
pwd

##############################################

# Load fasttree
module load fasttree
module list

# Infer a tree with fasttree with the GTR+CAT 
### GTR: General time reversible model 

## Input file to fasttree = OTUs155_rmN.fasta
## Output file to fasttree = newick_tree_OTUs155.tre 

FastTree -gtr -nt -fastest  < OTUs155_rmN.fasta > newick_tree_OTUs155.tre

