---
title: "Correlation OTU vs bins"
author: "Ruben Props"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: show
    highlight: haddock
    keep_md: yes
    theme: united
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
      toc_depth: 2
    css: report_styles.css
    df_print: paged
editor_options: 
  chunk_output_type: console
---


```{r setup, include = FALSE, warning = FALSE}
knitr::opts_chunk$set(eval = TRUE, 
                      echo = TRUE, 
                      cache = TRUE,
                      include = TRUE,
                      collapse = FALSE,
                      dependson = NULL,
                      engine = "R", # Chunks will always have R code, unless noted
                      error = TRUE,
                      fig.path="Figures/cached/",  # Set the figure options
                      fig.align = "center"
                      )
# Load libraries
library('dplyr')
library('ggplot2')
library("compositions")
library("grid")
library("gridExtra")
library("phyloseq")
library("ggrepel")
library("Phenoflow")
library("RColorBrewer")
source("./data/Chloroplasts_removed/old/Nov2017_Filtering/functions.R")
```


```{r FPCorSeq, fig.width = 10, fig.height= 10, fig.align='center'}
# Load phyloseq data
load("./data/Chloroplasts_removed/ByLake_Filtering/1in3/inland/inland_1in3_physeqs.RData")
load("./data/Chloroplasts_removed/ByLake_Filtering/5in10/inland/inland_5in10_physeqs.RData")
load("./data/Chloroplasts_removed/ByLake_Filtering/1in3/michigan/michigan_1in3_physeqs.RData")
load("./data/Chloroplasts_removed/ByLake_Filtering/5in10/michigan/michigan_5in10_physeqs.RData")
load("./data/Chloroplasts_removed/ByLake_Filtering/1in3/muskegon/muskegon_1in3_physeqs.RData")
load("./data/Chloroplasts_removed/ByLake_Filtering/5in10/muskegon/muskegon_5in10_physeqs.RData")

# get all 16S sample names
seq_samples <- c(sample_names(rare_inland_physeq_1in3_rel), 
                 sample_names(rare_michigan_physeq_1in3_rel),
                 sample_names(rare_muskegon_physeq_1in3_rel))
  
# Import FCM data and FCM data list mapping seq to FCM files
loc_fcs <- grep("_filtered", list.dirs("./data"),
     value = TRUE)[1:4]

# These are denoised already (see Filter_Count_FCS.R script) and 
# only have the four parameters of interest left (FL1/FL3/FSC/SSC)
fs1 <- read.flowSet(path = loc_fcs[1], pattern = "_filtered")
fs2 <- read.flowSet(path = loc_fcs[2], pattern = "_filtered")
fs3 <- read.flowSet(path = loc_fcs[3], pattern = "_filtered")
fs4 <- read.flowSet(path = loc_fcs[4], pattern = "_filtered")
fs <- rbind2(fs1,fs2); fs <- rbind2(fs, fs3)
fs <- rbind2(fs, fs4)
remove(fs1, fs2, fs3, fs4)

# Pool replicates
stubs <- c(unique(do.call(rbind, strsplit(flowCore::sampleNames(fs), 
                                        "_rep.\\.fcs_filtered"))
))

fs_pool <- FCS_pool(fs, stubs); remove(fs)

# Change some erronous names
flowCore::sampleNames(fs_pool) <- gsub("MI5", "M15", flowCore::sampleNames(fs_pool))

# Filter out samples that correspond to the sequencing data
labs_FCM <- read.csv2("./data/Chloroplasts_removed/old/Nov2017_Filtering/lab_FCM_16S.csv")
labs_FCM$Sample_fcm <- gsub("_rep.\\.fcs", "",labs_FCM$Sample_fcm)
labs_FCM <- labs_FCM %>% distinct()
labs_FCM$Sample_16S <- gsub("-", "", labs_FCM$Sample_16S)

# Check if some names were not found in the mapping file
flowCore::sampleNames(fs_pool)[!flowCore::sampleNames(fs_pool) %in% labs_FCM$Sample_fcm]
# sample_names(HNA_physeq_1in3)[!sample_names(HNA_physeq_1in3) %in% labs_FCM$Sample_16S]

# Transform with asinh
fs_pool <- transform(fs_pool,`FL1-H`=asinh(`FL1-H`), 
                                   `SSC-H`=asinh(`SSC-H`), 
                                   `FL3-H`=asinh(`FL3-H`), 
                                   `FSC-H`=asinh(`FSC-H`))

# Rename flow cytometry samples into sequencing names
flowCore::sampleNames(fs_pool) <- labs_FCM$Sample_16S[match(flowCore::sampleNames(fs_pool),
                                                             labs_FCM$Sample_fcm)]
# Order samples according to samples in phyloseq objects


# Normalize before calculating fingerprint
summary <- fsApply(x = fs_pool, FUN = function(x) apply(x, 2, max), use.exprs = TRUE)
maxval <- max(summary[,1])
mytrans <- function(x) x/maxval
fs_pool <- transform(fs_pool,`FL1-H`=mytrans(`FL1-H`),
                                  `FL3-H`=mytrans(`FL3-H`), 
                                  `SSC-H`=mytrans(`SSC-H`),
                                  `FSC-H`=mytrans(`FSC-H`))

# remove flow cytometry samples that are not present in phyloseq objects
fs_pool <- fs_pool[flowCore::sampleNames(fs_pool) %in% seq_samples]

# Calculate fingerprint
param <- c("FL1-H", "FL3-H", "FSC-H", "SSC-H")
fbasis <- flowBasis(fs_pool, param, nbin=128, 
                   bw=0.01, normalize=function(x) x)
# fbasis_pbin <- flowBasis(fs_pool, param, nbin=128, 
#                    bw=0.01, normalize=function(x) x,
#                    probBin = TRUE)
remove(fs_pool)

# Import lists with scores
path_scores <- list.files("./Scores")[c(1:6, 13:18)]

scores_df <- data.frame()
for(i in path_scores){
  tmp <- read.csv(paste("./Scores/", i, sep = ""))[, 1:2]
  if(!is.null(read.csv(paste("./Scores/", i, sep = ""))[, 7])){
      tmp2 <- read.csv(paste("./Scores/", i, sep = ""))[, 7]
        tmp <- cbind(tmp, gsub("_rel.*$","",i), gsub(".csv","", do.call(rbind, strsplit(i, "_"))[,5]),
               tmp2)
  } else {
    tmp <- cbind(tmp, gsub("_rel.*$","",i), gsub(".csv","", do.call(rbind, strsplit(i, "_"))[,5]),
               NA)
  }
  if(i == path_scores[1]){
    scores_df <- tmp
  } else {
      scores_df <- rbind(scores_df, tmp)
    }
}
colnames(scores_df) <- c("OTU", "Score", "method", "Environment", "p_kendall")

# sample names for each environment to partition calculates
sam_mi <- grep("M15|M45|110", seq_samples, value = TRUE)
sam_musk <- grep("M15|M45|110|Z", seq_samples, value = TRUE,
                 invert=TRUE)
sam_il <- grep("Z1", seq_samples, value = TRUE)
sams <- list(sam_mi, sam_musk, sam_il)
env <- c("Lake Michigan", "Muskegon Lake", "Inland Lakes")
frac <- rep(c("HNA","LNA"), each = 3)

################################################################################
# Perform CLR transformation on phyloseq objects
################################################################################
### Set 0 values to 1/(number of OTUs)²
otu_table(rare_inland_physeq_1in3_rel)[otu_table(rare_inland_physeq_1in3_rel) == 0] <-
  1/length(taxa_names(rare_inland_physeq_1in3_rel))^2
otu_table(rare_inland_physeq_5in10_rel)[otu_table(rare_inland_physeq_5in10_rel) == 0] <-
  1/length(taxa_names(rare_inland_physeq_5in10_rel))^2
otu_table(rare_michigan_physeq_1in3_rel)[otu_table(rare_michigan_physeq_1in3_rel) == 0] <-
  1/length(taxa_names(rare_michigan_physeq_1in3_rel))^2
otu_table(rare_michigan_physeq_5in10_rel)[otu_table(rare_michigan_physeq_5in10_rel) == 0] <-
  1/length(taxa_names(rare_michigan_physeq_5in10_rel))^2
otu_table(rare_muskegon_physeq_1in3_rel)[otu_table(rare_muskegon_physeq_1in3_rel) == 0] <-
  1/length(taxa_names(rare_muskegon_physeq_1in3_rel))^2
otu_table(rare_muskegon_physeq_5in10_rel)[otu_table(rare_muskegon_physeq_5in10_rel) == 0] <-
  1/length(taxa_names(rare_muskegon_physeq_5in10_rel))^2

### Normalize to sum of 1 per sample
rare_inland_physeq_1in3_rel_norm <- transform_sample_counts(rare_inland_physeq_1in3_rel, function(x) x/sum(x))
rare_inland_physeq_5in10_rel_norm <- transform_sample_counts(rare_inland_physeq_5in10_rel, function(x) x/sum(x))
rare_michigan_physeq_1in3_rel_norm <- transform_sample_counts(rare_michigan_physeq_1in3_rel, function(x) x/sum(x))
rare_michigan_physeq_5in10_rel_norm <- transform_sample_counts(rare_michigan_physeq_5in10_rel, function(x) x/sum(x))
rare_muskegon_physeq_1in3_rel_norm <- transform_sample_counts(rare_muskegon_physeq_1in3_rel, function(x) x/sum(x))
rare_muskegon_physeq_5in10_rel_norm <- transform_sample_counts(rare_muskegon_physeq_5in10_rel, function(x) x/sum(x))

### Check if sample sums are 1
sample_sums(rare_inland_physeq_1in3_rel_norm)
sample_sums(rare_inland_physeq_5in10_rel_norm)
sample_sums(rare_michigan_physeq_1in3_rel_norm)
sample_sums(rare_michigan_physeq_5in10_rel_norm)
sample_sums(rare_muskegon_physeq_1in3_rel_norm)
sample_sums(rare_muskegon_physeq_5in10_rel_norm)

### Run CLR transformation
rare_inland_physeq_1in3_rel_clr <- transform_sample_counts(rare_inland_physeq_1in3_rel_norm, compositions::clr)
rare_inland_physeq_5in10_rel_clr <- transform_sample_counts(rare_inland_physeq_5in10_rel_norm, compositions::clr)
rare_michigan_physeq_1in3_rel_clr <- transform_sample_counts(rare_michigan_physeq_1in3_rel_norm, compositions::clr)
rare_michigan_physeq_5in10_rel_clr <- transform_sample_counts(rare_michigan_physeq_5in10_rel_norm, compositions::clr)
rare_muskegon_physeq_1in3_rel_clr <- transform_sample_counts(rare_muskegon_physeq_1in3_rel_norm, compositions::clr)
rare_muskegon_physeq_5in10_rel_clr <- transform_sample_counts(rare_muskegon_physeq_5in10_rel_norm, compositions::clr)

################################################################################
# Run FPcorSEQ at diffferent thresholds for both LNA and HNA lasso run
################################################################################

## for 1seq3 
fixed_thresh <- 0.35
tuned_thresh <- 0.15
list_fix <- list(scores_df %>% dplyr::filter(method == "hnascores_otus_1seq3" & Score > fixed_thresh & Environment == "Michigan"), 
                    scores_df %>% dplyr::filter(method == "hnascores_otus_1seq3" & Score > fixed_thresh & Environment == "Inland"), 
                    scores_df %>% dplyr::filter(method == "hnascores_otus_1seq3" & Score > fixed_thresh & Environment == "Muskegon"),
                 scores_df %>% dplyr::filter(method == "lnascores_otus_1seq3" & Score > fixed_thresh & Environment == "Muskegon"),
                 scores_df %>% dplyr::filter(method == "lnascores_otus_1seq3" & Score > fixed_thresh & Environment == "Muskegon"),
                 scores_df %>% dplyr::filter(method == "lnascores_otus_1seq3" & Score > fixed_thresh & Environment == "Muskegon")
)

HNA_physeq_1in3 <- rep(list(rare_michigan_physeq_1in3_rel,  rare_muskegon_physeq_1in3_rel, rare_inland_physeq_1in3_rel),2)


# Calculate correlations for each environment separately and then concantenate
# results
for(i in 1:length(rep(sams,2))){
  HNA_physeq_1in3_fix <- prune_taxa(taxa = as.character(list_fix[[i]]$OTU), HNA_physeq_1in3[[i]])
  phy_tmp <- prune_samples(rep(sams,2)[[i]], HNA_physeq_1in3_fix)
  fp_tmp <- fbasis
  fp_tmp@basis <- fp_tmp@basis[rownames(fp_tmp@basis) %in% rep(sams,2)[[i]], ]
  ################################################################################
  # Perform CLR transformation on flowbasis
  ################################################################################
  # fp_tmp@basis[fp_tmp@basis == 0] <- 1/(ncol(fp_tmp@basis)^2)
  # fp_tmp@basis <- apply(fp_tmp@basis, 1, FUN = function(x) x/sum(x))
  # fp_tmp@basis <- apply(fp_tmp@basis, 1, FUN = function(x) compositions::clr(x))
  ################################################################################
  res_HNA_1in3_tmp <- FPcorSeq(phy = phy_tmp, fp = fp_tmp,
                        cor_thresh = 0.1, fp_thresh = 1e-4, 
                        cor_m = "kendall")
  res_HNA_1in3_tmp <- data.frame(res_HNA_1in3_tmp, Environment =  rep(env,2)[i], fraction = frac[i])
  if(i == 1) {
    res_HNA_1in3_fix <- res_HNA_1in3_tmp
  } else{
    res_HNA_1in3_fix <- rbind(res_HNA_1in3_fix, res_HNA_1in3_tmp)
  }
}

# res_HNA_1in3_fix <- FPcorSeq(phy = HNA_physeq_1in3_fix, fp = fbasis,
#                         cor_thresh = 0.1, fp_thresh = 1e-5, 
#                         cor_m = "kendall")
scores_sb <- scores_df %>% dplyr::filter(grepl("*1seq3*", method))
scores_sb$Environment <- plyr::revalue(scores_sb$Environment, c("Michigan"="Lake Michigan",
                                                                "Muskegon"="Muskegon Lake",
                                                                "Inland" = "Inland Lakes"))

res_NA_1in3_fix <- dplyr::left_join(res_HNA_1in3_fix, scores_sb, by = c("taxa" = "OTU", "Environment"))
res_NA_1in3_fix$fraction <- as.character(res_NA_1in3_fix$fraction)
res_NA_1in3_fix$Pool <- res_NA_1in3_fix$fraction
res_NA_1in3_fix$Pool[res_NA_1in3_fix$fraction == "HNA"][res_NA_1in3_fix$taxa[res_NA_1in3_fix$fraction == "HNA"] %in% res_NA_1in3_fix$taxa[res_NA_1in3_fix$fraction == "LNA"]] <- "Shared"
res_NA_1in3_fix$Pool[res_NA_1in3_fix$fraction == "LNA"][res_NA_1in3_fix$taxa[res_NA_1in3_fix$fraction == "LNA"] %in% res_NA_1in3_fix$taxa[res_NA_1in3_fix$fraction == "HNA"]] <- "Shared"
res_NA_1in3_fix$Pool <- factor(res_NA_1in3_fix$Pool, levels = c("LNA", "Shared", "HNA"))

### Same analysis for 5seq10 samples
fixed_thresh <- 0.35
list_fix <- list(scores_df %>% dplyr::filter(method == "hnascores_otus_5seq10" 
                                             & Score > fixed_thresh & Environment == "Michigan"), 
                 scores_df %>% dplyr::filter(method == "hnascores_otus_5seq10" 
                                             & Score > fixed_thresh & Environment == "Inland"), 
                 scores_df %>% dplyr::filter(method == "hnascores_otus_5seq10"
                                             & Score > fixed_thresh & Environment == "Muskegon"),
                 scores_df %>% dplyr::filter(method == "lnascores_otus_5seq10" 
                                             & Score > fixed_thresh & Environment == "Muskegon"),
                 scores_df %>% dplyr::filter(method == "lnascores_otus_5seq10" 
                                             & Score > fixed_thresh & Environment == "Muskegon"),
                 scores_df %>% dplyr::filter(method == "lnascores_otus_5seq10" 
                                             & Score > fixed_thresh & Environment == "Muskegon")
)

HNA_physeq_5in10 <- rep(list(rare_michigan_physeq_5in10_rel,  rare_muskegon_physeq_5in10_rel, rare_inland_physeq_5in10_rel),2)


# Calculate correlations for each environment separately and then concantenate
# results
for(i in 1:length(rep(sams,2))){
  HNA_physeq_5in10_fix <- prune_taxa(taxa = as.character(list_fix[[i]]$OTU), HNA_physeq_5in10[[i]])
  phy_tmp <- prune_samples(rep(sams,2)[[i]], HNA_physeq_5in10_fix)
  fp_tmp <- fbasis
  fp_tmp@basis <- fp_tmp@basis[rownames(fp_tmp@basis) %in% rep(sams,2)[[i]], ]
  ################################################################################
  # Perform CLR transformation on flowbasis
  ################################################################################
  # fp_tmp@basis[fp_tmp@basis == 0] <- 1/(ncol(fp_tmp@basis)^2)
  # fp_tmp@basis <- apply(fp_tmp@basis, 1, FUN = function(x) x/sum(x))
  # fp_tmp@basis <- apply(fp_tmp@basis, 1, FUN = function(x) compositions::clr(x))
  ################################################################################
  res_HNA_5in10_tmp <- FPcorSeq(phy = phy_tmp, fp = fp_tmp,
                        cor_thresh = 0.1, fp_thresh = 1e-4, 
                        cor_m = "kendall")
  res_HNA_5in10_tmp <- data.frame(res_HNA_5in10_tmp, Environment = rep(env,2)[i], fraction = frac[i])
  if(i == 1) {
    res_HNA_5in10_fix <- res_HNA_5in10_tmp
  } else{
    res_HNA_5in10_fix <- rbind(res_HNA_5in10_fix, res_HNA_5in10_tmp)
  }
}

scores_sb <- scores_df %>% dplyr::filter(grepl("*5seq10*", method))
scores_sb$Environment <- plyr::revalue(scores_sb$Environment, c("Michigan"="Lake Michigan",
                                                                "Muskegon"="Muskegon Lake",
                                                                "Inland" = "Inland Lakes"))
res_NA_5in10_fix <- dplyr::left_join(res_HNA_5in10_fix, scores_sb, by = c("taxa" = "OTU", "Environment"))
res_NA_5in10_fix$fraction <- as.character(res_NA_5in10_fix$fraction)
res_NA_5in10_fix$Pool <- res_NA_5in10_fix$fraction
res_NA_5in10_fix$Pool[res_NA_5in10_fix$fraction == "HNA"][res_NA_5in10_fix$taxa[res_NA_5in10_fix$fraction == "HNA"] %in% res_NA_5in10_fix$taxa[res_NA_5in10_fix$fraction == "LNA"]] <- "Shared"
res_NA_5in10_fix$Pool[res_NA_5in10_fix$fraction == "LNA"][res_NA_5in10_fix$taxa[res_NA_5in10_fix$fraction == "LNA"] %in% res_NA_5in10_fix$taxa[res_NA_5in10_fix$fraction == "HNA"]] <- "Shared"
res_NA_5in10_fix$Pool <- factor(res_NA_5in10_fix$Pool, levels = c("LNA", "Shared", "HNA"))

# Make heatmap plots
# Visualize correlations for top OTUs
for(i in 1:3){
  v_LNA_1in3_fix <- res_NA_1in3_fix %>% dplyr::filter(Environment == env[i], Pool == "LNA") %>% 
  ggplot2::ggplot(ggplot2::aes(`FL1.H`, `FL3.H`, z = cor))+
  ggplot2::geom_tile(ggplot2::aes(fill=cor)) +
  # ggplot2::geom_point(size = 1, ggplot2::aes(fill=cor), shape =22,
                      # color = "transparent")+
  ggplot2::scale_fill_distiller(palette="RdBu", na.value="white", limits = c(-0.6,0.6)) + 
  # ggplot2::stat_contour(ggplot2::aes(fill=..level..), geom="polygon", binwidth=0.1)+
  ggplot2::theme_bw()+
  # ggplot2::geom_contour(color = "white", alpha = 1)+
  facet_wrap(~taxa, nrow = 2)+
  ylim(0,150)+
  xlim(40,150)+
    theme(axis.title=element_text(size=16), strip.text=element_text(size=16),
        legend.title=element_text(size=15),legend.text=element_text(size=14),
        axis.text = element_text(size=14),title=element_text(size=20),
        strip.background=element_rect(fill=adjustcolor("lightgray",0.2))
        #,panel.grid.major = element_blank(), panel.grid.minor = element_blank()
        )+
  ggtitle("LNA population")
  
  if(dim(res_NA_1in3_fix %>% dplyr::filter(Environment == env[i], Pool == "Shared"))[1]>0){
      v_shared_1in3_fix <- res_NA_1in3_fix %>% dplyr::filter(Environment == env[i], Pool == "Shared") %>% 
  ggplot2::ggplot(ggplot2::aes(`FL1.H`, `FL3.H`, z = cor))+
  ggplot2::geom_tile(ggplot2::aes(fill=cor)) +
  # ggplot2::geom_point(size = 1, ggplot2::aes(fill=cor), shape =22,
                      # color = "transparent")+
  ggplot2::scale_fill_distiller(palette="RdBu", na.value="white", limits = c(-0.6,0.6)) + 
  # ggplot2::stat_contour(ggplot2::aes(fill=..level..), geom="polygon", binwidth=0.1)+
  ggplot2::theme_bw()+
  # ggplot2::geom_contour(color = "white", alpha = 1)+
  facet_wrap(~taxa, nrow = 2)+
  ylim(0,150)+
  xlim(40,150)+
    theme(axis.title=element_text(size=16), strip.text=element_text(size=16),
        legend.title=element_text(size=15),legend.text=element_text(size=14),
        axis.text = element_text(size=14),title=element_text(size=20),
        strip.background=element_rect(fill=adjustcolor("lightgray",0.2))
        #,panel.grid.major = element_blank(), panel.grid.minor = element_blank()
        )+
  ggtitle("Shared population")
    
    png(file = paste("./fingerprint_plots/FPcorSEQ_1in3_shared_notrans_", env[i], ".png", sep =""), width = 7, height = 6, 
    units  = "in", res = 500, bg = "transparent")
    print(v_shared_1in3_fix)
    dev.off()
  }
        v_HNA_1in3_fix <- res_NA_1in3_fix %>% dplyr::filter(Environment == env[i], Pool == "HNA") %>% 
  ggplot2::ggplot(ggplot2::aes(`FL1.H`, `FL3.H`, z = cor))+
  ggplot2::geom_tile(ggplot2::aes(fill=cor)) +
  # ggplot2::geom_point(size = 1, ggplot2::aes(fill=cor), shape =22,
                      # color = "transparent")+
  ggplot2::scale_fill_distiller(palette="RdBu", na.value="white", limits = c(-0.6,0.6)) + 
  # ggplot2::stat_contour(ggplot2::aes(fill=..level..), geom="polygon", binwidth=0.1)+
  ggplot2::theme_bw()+
  # ggplot2::geom_contour(color = "white", alpha = 1)+
  facet_wrap(~taxa, nrow = 2)+
  ylim(0,150)+
  xlim(40,150)+
    theme(axis.title=element_text(size=16), strip.text=element_text(size=16),
        legend.title=element_text(size=15),legend.text=element_text(size=14),
        axis.text = element_text(size=14),title=element_text(size=20),
        strip.background=element_rect(fill=adjustcolor("lightgray",0.2))
        #,panel.grid.major = element_blank(), panel.grid.minor = element_blank()
        )+
  ggtitle("HNA population")

png(file = paste("./fingerprint_plots/FPcorSEQ_1in3_unique_notrans_", env[i], ".png", sep =""), width = 20, height = 10, 
    units  = "in", res = 500, bg = "transparent")
grid_arrange_shared_legend(v_LNA_1in3_fix, v_HNA_1in3_fix, ncol = 2, position = "right")
dev.off()
}

# Make heatmap plots
# Visualize correlations for top OTUs

for(i in 1:3){
  v_LNA_5in10_fix <- res_NA_5in10_fix %>% dplyr::filter(Environment == env[i], Pool == "LNA") %>% 
  ggplot2::ggplot(ggplot2::aes(`FL1.H`, `FL3.H`, z = cor))+
  ggplot2::geom_tile(ggplot2::aes(fill=cor)) +
  # ggplot2::geom_point(size = 1, ggplot2::aes(fill=cor), shape =22,
                      # color = "transparent")+
  ggplot2::scale_fill_distiller(palette="RdBu", na.value="white", limits = c(-0.6,0.6)) + 
  # ggplot2::stat_contour(ggplot2::aes(fill=..level..), geom="polygon", binwidth=0.1)+
  ggplot2::theme_bw()+
  # ggplot2::geom_contour(color = "white", alpha = 1)+
  facet_wrap(~taxa, nrow = 2)+
  ylim(0,150)+
  xlim(40,150)+
    theme(axis.title=element_text(size=16), strip.text=element_text(size=16),
        legend.title=element_text(size=15),legend.text=element_text(size=14),
        axis.text = element_text(size=14),title=element_text(size=20),
        strip.background=element_rect(fill=adjustcolor("lightgray",0.2))
        #,panel.grid.major = element_blank(), panel.grid.minor = element_blank()
        )+
    ggtitle("LNA population")
  
    v_shared_5in10_fix <- res_NA_5in10_fix %>% dplyr::filter(Environment == env[i], Pool == "Shared") %>% 
  ggplot2::ggplot(ggplot2::aes(`FL1.H`, `FL3.H`, z = cor))+
  ggplot2::geom_tile(ggplot2::aes(fill=cor)) +
  # ggplot2::geom_point(size = 1, ggplot2::aes(fill=cor), shape =22,
                      # color = "transparent")+
  ggplot2::scale_fill_distiller(palette="RdBu", na.value="white", limits = c(-0.6,0.6)) + 
  # ggplot2::stat_contour(ggplot2::aes(fill=..level..), geom="polygon", binwidth=0.1)+
  ggplot2::theme_bw()+
  # ggplot2::geom_contour(color = "white", alpha = 1)+
  facet_wrap(~taxa, nrow = 2)+
  ylim(0,150)+
  xlim(40,150)+
    theme(axis.title=element_text(size=16), strip.text=element_text(size=16),
        legend.title=element_text(size=15),legend.text=element_text(size=14),
        axis.text = element_text(size=14),title=element_text(size=20),
        strip.background=element_rect(fill=adjustcolor("lightgray",0.2))
        #,panel.grid.major = element_blank(), panel.grid.minor = element_blank()
        )+
      ggtitle("Shared population")
    
        v_HNA_5in10_fix <- res_NA_5in10_fix %>% dplyr::filter(Environment == env[i], Pool == "HNA") %>% 
  ggplot2::ggplot(ggplot2::aes(`FL1.H`, `FL3.H`, z = cor))+
  ggplot2::geom_tile(ggplot2::aes(fill=cor)) +
  # ggplot2::geom_point(size = 1, ggplot2::aes(fill=cor), shape =22,
                      # color = "transparent")+
  ggplot2::scale_fill_distiller(palette="RdBu", na.value="white", limits = c(-0.6,0.6)) + 
  # ggplot2::stat_contour(ggplot2::aes(fill=..level..), geom="polygon", binwidth=0.1)+
  ggplot2::theme_bw()+
  # ggplot2::geom_contour(color = "white", alpha = 1)+
  facet_wrap(~taxa, nrow = 2)+
  ylim(0,150)+
  xlim(40,150)+
    theme(axis.title=element_text(size=16), strip.text=element_text(size=16),
        legend.title=element_text(size=15),legend.text=element_text(size=14),
        axis.text = element_text(size=14),title=element_text(size=20),
        strip.background=element_rect(fill=adjustcolor("lightgray",0.2))
        #,panel.grid.major = element_blank(), panel.grid.minor = element_blank()
        )+
  ggtitle("HNA population")


png(file = paste("./fingerprint_plots/FPcorSEQ_5in10_unique_notrans_", env[i], ".png", sep =""), width = 20, height = 10, 
    units  = "in", res = 500, bg = "transparent")
grid_arrange_shared_legend(v_LNA_5in10_fix, v_HNA_5in10_fix, ncol = 2, position = "right")
dev.off()

png(file = paste("./fingerprint_plots/FPcorSEQ_5in10_shared_notrans_", env[i], ".png", sep =""), width = 7, height = 6, 
    units  = "in", res = 500, bg = "transparent")
print(v_shared_5in10_fix)
dev.off()
}

# From here on focus on Muskegon lake
res_NA_5in10_musk <- res_NA_5in10_fix %>% dplyr::filter(Environment == env[2])
res_NA_1in3_musk <- res_NA_1in3_fix %>% dplyr::filter(Environment == env[2])

res_NA_5in10_musk_shared <- res_NA_5in10_musk %>% dplyr::filter(Pool == "Shared")

v_musk_5in10_shared <- res_NA_5in10_musk_shared %>% 
  ggplot2::ggplot(ggplot2::aes(`FL1.H`, `FL3.H`, z = cor))+
  ggplot2::geom_tile(ggplot2::aes(fill=cor)) +
  # ggplot2::geom_point(size = 1, ggplot2::aes(fill=cor), shape =22,
                      # color = "transparent")+
  ggplot2::scale_fill_distiller("Kendall's\ntau-b\n", palette="RdBu", na.value="white", limits = c(-0.6,0.6),
                                breaks = round(seq(-0.6,0.6,0.3), 1)) + 
  # ggplot2::stat_contour(ggplot2::aes(fill=..level..), geom="polygon", binwidth=0.1)+
  ggplot2::theme_bw()+
  # ggplot2::geom_contour(color = "white", alpha = 1)+
  facet_wrap(~taxa, ncol = 5)+
  ylim(0,150)+
  xlim(40,150)+
    theme(axis.title=element_text(size=16), strip.text=element_text(size=16),
        legend.text=element_text(size=14),
        axis.text = element_text(size=14),title=element_text(size=20),
        strip.background=element_rect(fill=adjustcolor("lightgray",0.2)),
        legend.title = element_text("Kendall's\ntau-b\n",size=15)
        #,panel.grid.major = element_blank(), panel.grid.minor = element_blank()
        )+
      ggtitle("")+
  xlab("Green fluorescence intensity (FL1-H - a.u.)")+
  ylab("Red fluorescence intensity (FL3-H - a.u.)")

# Make extra factor for coloring background of panels according to p_kendal
res_NA_5in10_musk_HNA <- res_NA_5in10_musk %>% dplyr::filter(Pool == "HNA", method == "hnascores_otus_5seq10")
res_NA_5in10_musk_LNA <- res_NA_5in10_musk %>% dplyr::filter(Pool == "LNA", method == "lnascores_otus_5seq10")
res_NA_5in10_musk_HNA$cor_sign <- factor(res_NA_5in10_musk_HNA$p_kendall > 0)
res_NA_5in10_musk_LNA$cor_sign <- factor(res_NA_5in10_musk_LNA$p_kendall > 0)

#Create a data frame with the faceting variables
# and some dummy data (that will be overwritten)
tp <- res_NA_5in10_musk_HNA
tp$FL1.H <- tp$FL3.H <- 1

v_musk_5in10_HNA <- res_NA_5in10_musk_HNA %>% 
  ggplot2::ggplot(ggplot2::aes(`FL1.H`, `FL3.H`, z = cor))+
  geom_rect(data = subset(tp, cor_sign == "TRUE"), fill = "#9CB991", xmin = -Inf, xmax = Inf,
            ymin = -Inf,ymax = Inf, alpha = 0.09) +
  geom_rect(data = subset(tp, cor_sign == "FALSE"), fill = "#FBD5D7", xmin = -Inf, xmax = Inf,
            ymin = -Inf,ymax = Inf, alpha = 0.09) +
  ggplot2::geom_tile(ggplot2::aes(fill=cor))+
  ggplot2::scale_fill_distiller("Kendall's\ntau-b\n", palette="RdBu", na.value="white", limits = c(-0.6,0.6),
                                breaks = round(seq(-0.6,0.6,0.3), 1)) + 
  # ggplot2::stat_contour(ggplot2::aes(fill=..level..), geom="polygon", binwidth=0.1)+
  ggplot2::theme_bw()+
  # ggplot2::geom_contour(color = "white", alpha = 1)+
  facet_wrap(~taxa, ncol = 5)+
  ylim(0,150)+
  xlim(40,150)+
    theme(axis.title=element_text(size=16), strip.text=element_text(size=16),
        legend.text=element_text(size=14),
        axis.text = element_text(size=14),title=element_text(size = 20),
        strip.background=element_rect(fill=adjustcolor("lightgray",0.2)),
        panel.grid.major = element_line(colour = "black"),
        panel.grid.minor = element_line(colour = "black"),
        legend.title = element_text("Kendall's\ntau-b\n",size=15)
        #,panel.grid.major = element_blank(), panel.grid.minor = element_blank()
        )+
      ggtitle("")+
  xlab("Green fluorescence intensity (FL1-H - a.u.)")+
  ylab("Red fluorescence intensity (FL3-H - a.u.)")

print(v_musk_5in10_HNA)

#Create a data frame with the faceting variables
# and some dummy data (that will be overwritten)
tp <- res_NA_5in10_musk_LNA
tp$FL1.H <- tp$FL3.H <- 1

v_musk_5in10_LNA <- res_NA_5in10_musk_LNA %>% 
  ggplot2::ggplot(ggplot2::aes(`FL1.H`, `FL3.H`, z = cor))+
  ggplot2::theme_bw()+
  geom_rect(data = subset(tp, cor_sign == "TRUE"), fill = "#9CB991", xmin = -Inf, xmax = Inf,
            ymin = -Inf,ymax = Inf, alpha = 0.09) +
  geom_rect(data = subset(tp, cor_sign == "FALSE"), fill = "#FBD5D7", xmin = -Inf, xmax = Inf,
            ymin = -Inf,ymax = Inf, alpha = 0.09) +
  ggplot2::geom_tile(ggplot2::aes(fill=cor))+
  ggplot2::scale_fill_distiller("Kendall's\ntau-b\n", palette="RdBu", na.value="white", limits = c(-0.6,0.6),
                                breaks = round(seq(-0.6,0.6,0.3), 1), guide = "colourbar") + 
  # ggplot2::stat_contour(ggplot2::aes(fill=..level..), geom="polygon", binwidth=0.1)+
  # ggplot2::geom_contour(color = "white", alpha = 1)+
  facet_wrap(~taxa, ncol = 5)+
  ylim(0,150)+
  xlim(40,150)+ 
    theme(axis.title=element_text(size=16), strip.text=element_text(size=16),
        legend.title=element_text(size=15),legend.text=element_text(size=14),
        axis.text = element_text(size=14),title=element_text(size = 20),
        strip.background=element_rect(fill=adjustcolor("lightgray",0.2)),
        panel.grid.major = element_line(colour = "black"),
        panel.grid.minor = element_line(colour = "black")
        #,panel.grid.major = element_blank(), panel.grid.minor = element_blank()
        )+
      ggtitle("")+
  xlab("Green fluorescence intensity (FL1-H - a.u.)")+
  ylab("Red fluorescence intensity (FL3-H - a.u.)")

# Export figures
png(file = paste("./fingerprint_plots/FPcorSEQ_5in10_unique_notrans_LNA_muskegon.png", sep =""), width = 15, height = 8, 
    units  = "in", res = 500, bg = "transparent")
print(v_musk_5in10_LNA)
dev.off()

png(file = paste("./fingerprint_plots/FPcorSEQ_5in10_unique_notrans_HNA_muskegon.png", sep =""), width = 15, height = 8, 
    units  = "in", res = 500, bg = "transparent")
print(v_musk_5in10_HNA)
dev.off()

png(file = paste("./fingerprint_plots/FPcorSEQ_5in10_unique_notrans_shared_muskegon.png", sep =""), width = 15, height = 4, 
    units  = "in", res = 500, bg = "transparent")
print(v_musk_5in10_shared)
dev.off()



```
